apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policyset-openshift-plus-clusters
placementRef:
  name: placement-policyset-openshift-plus-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: policy-advanced-managed-cluster-security
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: policy-compliance-operator-install
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: policy-acs-central-ca-bundle
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: placement-policyset-openshift-plus-clusters
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}
