apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policyset-openshift-plus-hub
placementRef:
  name: placement-policyset-openshift-plus-hub
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: policy-advanced-cluster-security-central
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: policy-config-quay
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: policy-object-storage
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: policy-odf
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: policy-ocm-observability
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: placement-policyset-openshift-plus-hub
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: local-cluster, operator: In, values: ["true"]}
